# Generated by Django 5.0.1 on 2024-02-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('available_stock', models.FloatField(default=0)),
                ('price_per_unit', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'ordering': ['-price_per_unit'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('ingredients', models.ManyToManyField(blank=True, to='inventory.ingredientmodel')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitemmodel')),
            ],
            options={
                'verbose_name': 'Sale',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRequirementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredientmodel')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitemmodel')),
            ],
            options={
                'verbose_name': 'Recipe Requirement',
            },
        ),
    ]
