# Generated by Django 5.0.1 on 2024-01-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredientmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemmodel',
            old_name='required_ingredients',
            new_name='ingredients',
        ),
    ]
