# Generated by Django 5.0.1 on 2024-01-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_required_ingredients_menuitemmodel_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemmodel',
            options={'ordering': ['-price'], 'verbose_name': 'Menu Item'},
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='available_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
